[package]
name = "dadosod"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# TODO: Upstream needed changes
ppc750cl = { git="https://github.com/terorie/ppc750cl", rev="619c935dc4979ff54abad7ee99412c2e257c03ab", package='ppc750cl' }
dol = { git="https://github.com/terorie/ppc750cl", rev="619c935dc4979ff54abad7ee99412c2e257c03ab", package='dol' }

argh = "0.1"